// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxwnoSLya_TfU3CK39wcPN1HBmLK2Xe9s',
    appId: '1:818661847615:web:6b03f3657c6b7fa11e7e8a',
    messagingSenderId: '818661847615',
    projectId: 'medical-projet-licence',
    authDomain: 'medical-projet-licence.firebaseapp.com',
    storageBucket: 'medical-projet-licence.appspot.com',
    measurementId: 'G-C94GQLS3B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4_FXu6xukPmbYa4IhK3uuOdtHJ7bEn3Y',
    appId: '1:818661847615:android:070dfe79a22bbb341e7e8a',
    messagingSenderId: '818661847615',
    projectId: 'medical-projet-licence',
    storageBucket: 'medical-projet-licence.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0AbOC0bZniKo54qd6Q_Ihdzi2nq_dA0',
    appId: '1:818661847615:ios:08983c6321052a421e7e8a',
    messagingSenderId: '818661847615',
    projectId: 'medical-projet-licence',
    storageBucket: 'medical-projet-licence.appspot.com',
    androidClientId: '818661847615-64ch9qoc3k71k3suq8eu9ttgra325s3k.apps.googleusercontent.com',
    iosClientId: '818661847615-s2c1cco1p8jrjftjecegsd09ipnbd2mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalProjet',
  );
}
